# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
