# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='faqinfo',
            name='heading',
            field=models.CharField(default='Frequently Asked Questions', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqinfo',
            name='subheading',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqinfo',
            name='title',
            field=models.CharField(default='FAQ', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='heading',
            field=models.CharField(default='Our Team', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='subheading',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='title',
            field=models.CharField(default='Team', max_length=256),
            preserve_default=False,
        ),
    ]
