# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.CharField(max_length=256),
        ),
    ]
