# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blurb',
            name='link',
            field=models.CharField(max_length=256),
        ),
    ]
